/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package td1;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //Paire a = new Paire<Integer,String>(2, "Yo");
        //System.out.println(a.toString());
    }
}
